### ISSUE TITLE
Missing monorail.ipxe

### ISSUE THREAD

**Issue by jimmypw** [RackHD/on-tftp#32]
I have noticed that in your 'example' deployment the vagrant image comes pre-loaded with the monorail.ipxe image. However in the on-tftp code repository there is no reference to this file other than the static/tftp directory where it is supposed to exist. Nor is there an NPM script to use in order to acquire it.

Where are we supposed to get the file from?

**Comment by heckj** [comment]
Evening @jimmypw,

monorail.ipxe is only one file needed - there's several. The files are available in binary form to download from bintray, and the Ansible role that we use in creating our example  Vagrant instance shows the details at https://github.com/RackHD/RackHD/blob/master/packer/ansible/roles/images/tasks/main.yml

The files themselves can be "rebuilt from source" following the instructions within the on-imagebuilder repo (https://github.com/RackHD/on-imagebuilder/) - we use TravisCI to build the binaries and host them on bintray for our example setup.
